## This is test deployment for Kubernetes platforms.
## This is not intended to be used in production.
##
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-rails
  name: test-rails
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-rails
  template:
    metadata:
      labels:
        app: test-rails
    spec:
      containers:
      - image: bitnami/rails
        name: rails
